sonar.projectKey=jiangxincode_SPMP8000Emu
sonar.projectName=SPMP8000Emu
sonar.organization=jiangxincode-github

sonar.sources=crates
sonar.exclusions=**/target/**
sonar.sourceEncoding=UTF-8

sonar.rust.cobertura.reportPaths=coverage/cobertura.xml
